dist: xenial
sudo: false
language: scala
jdk:
- openjdk11
scala:
- 2.13.2
env:
  global:
  - secure: HQwandKNZc/PosBCdKCMyo6MZ75+d8AUmIEOdh/+XVFRy9KZ7mCSEdhUVo9ZRB5GfkKcP/74ZaNdPoDSi/1f36LyXEL2SXJel18HsG1cSxtUi5VKZoW6Zsxr9Swm1KwKbDhYrH6oimYZ3fF4bl/8wnJNUGKnGMSsYD4kwA6jl8SG8JSoa7btltI8JUBXbH8tZojipZyNu1V4NiB7oKHwvzuG8eYizVC6gNjcCDqeV04/+UJhl07I9TpvOO7b8IBZ31D5MljWSKKpZV9622y1OQf6e4akE5wNnyVmUk1WZSXeb1+I0NcOY8QtTTX2Ohg6xtO4gKKphN6zG9Zvz6CiO5LyJelOa3C/B9iss0xz5cmbE62APcT09B3feUjFt4ZBcA/ylDWMEOoQiiH530iZqtjlXmz5TKve0S44VQ70hr7fzqtRo+hfx7fz6od/cGaBIN+BFjgmPHJ8GoEYbvho+RMyDvLwyFT4y0f63qnCPkQ+6viHkRVWYqt9pAx0eq+8u+nJ9wqo5im0ffrQn7VEjGT5GT+cvz4aS28D28F7GvHVs+IOVS0gs0CaYsoaJRK+muxPg04RQ55EhssGjiMwYfONX/u7gZ5K9pTUVnJiMx75K6YCTl8AOeQb5ws7Zo2pfZyhkcDeHsg0QQ9uQ1fAboQtc/Dl/5MnhWum7qTSQf8=
  - secure: v1Na5njUWv7HNRBjJGcsWBk5Im72pqkcYsKB7tIHmP1XQCACDeLANGoJrNlheYHLY30jrCC1t6Wd0wWOO4NG9HblJKSygRSigz0Y2wJtSnC8SZaUInIwqWq+K7WPgjO4qzMXAl0iFIqJKm/utJ2/GoJw/8Bpz1a8msJNBXalusKVowMeFeoOhadYvcynO3AQd9MkFgpkq48jzL00S8ssO7PYDbq7qw2ivaj0UYxCqrOEbgsBp4gu73mb+hDMR/AYEmfY2C7rYUxW7HMmv5dqsN328Ggk7voHOlArsMCj3t1N5UKWsBVUtcrYUb7yf2DeyUhjidYXgGgSmA7cw8SwPW2ln2GXgXj8z7JNOeaAi9pV1l2EfJT1Sq3iUBwvdwSD7rxRQ9TC73naafjniJvJp/Dh84Md9A3AVvV5ycc1bTdyQNNOEjZiv3idjnKDGCtj48HTYK4MlPQ0PJVSPuXZCMnGpgzgUr3iyMpJ1ASX/DQVUFBRl/lFt3sfuxtIgRk9vgn7F56fAX4QQsnOcuBDwb3v+6MvwHynUH7Fk6Ua8jlhMVrthlvPlmjLopQZr8GTfBMhc1t8kxdkNKWN3aYiSlfQqTJvhT8O+pKVJvfwPJTazovQQDgbuQ5GcGXFYCsX/gmGUTdHkhh3UR8e+BTtEXllWDQO7vnHYKAfrCDqX1Y=
  - secure: C9wvcSxEmG4uwyl7ip6G+sDaSOv+PYHjqvlBxNKNG/2vFI7HrCGBMg4MU8GMqTzSeJ2d7iBTTnC2IkaHoOyX7L33hPwZv4GqSv4/8qfPePzBlcmNwk+j3AHTgj4hUtHbDEiSnNgjslZHFYx6PhjAS4T4EAeKjTCayl/HpcezT0VyIDXApJta9pxFUunOxX+TgCNsoiWjdCesfLFX6JhHk8SKICZUC2i1GnnHcpJeShO/zyGfun/haD8LfgGJtrBZ8bY4B8SugncTm+wOg/xw0jPltyH8cPdgq3fK1qY/fyguN50V3MhRkR7Dah4WKqKN0wKhg5mgI23FKESDd3mvlIeKHpj/99b+/g8cLPwi+sXcTmJ2WgUMPHRTenHfUdX7KHDZnqVgqqlkh9kLjXPICHLnQ4a3eVzLHZceOQzBD9DQEK5BCi0Vt6tKuM8CNIa9janiEmIexCFV2t775EqDdJdZ4hom9b8MCdspCB2Cd4BpUFIFLUP/vwOvxmWGjuagho9YyNOZ7cxnQYV1wCqvkmlNNgk3GBx8fCSj/XjvdLIqWMfHkFXgB+BNMEtEBamiJMw1VpkbnchecTClXEKJZgb82uOF5lD1T0JXFKEzDz1tBXvakdJFm6nTMSMXUke+nW7wVBdUDjww3021Zrbjyc8NlpWL6auUpeoAMBWSD8k=
before_install:
- if [[ -n "${TRAVIS_TAG}" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_227846deebd3_key -iv $encrypted_227846deebd3_iv -in .travis/secrets.tar.enc -out .travis/local.secrets.tar -d; tar xv -C .travis -f .travis/local.secrets.tar;
  fi
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalafmtCheck scalafmtSbtCheck
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
- if [[ -n "${TRAVIS_TAG}" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    sbt -Dsbt.color=always -Dsbt.supershell=false ++$TRAVIS_SCALA_VERSION +releaseEarly;
  fi
- bash <(curl -s https://codecov.io/bash)
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
